// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp4FNFa0J8hVyqQ8QW7865ZcQncoTJfFc',
    appId: '1:126877803192:android:51c9ca178c41d237158a4d',
    messagingSenderId: '126877803192',
    projectId: 'cinema-ticket-booking-8cdb2',
    storageBucket: 'cinema-ticket-booking-8cdb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc29zlWxd7pJ_pKg0QhxJz0-cgGYRrl4Y',
    appId: '1:126877803192:ios:d5acd61e25282b45158a4d',
    messagingSenderId: '126877803192',
    projectId: 'cinema-ticket-booking-8cdb2',
    storageBucket: 'cinema-ticket-booking-8cdb2.appspot.com',
    iosClientId: '126877803192-2jcv26qq6a54adj4ar4kolmrado624nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaApp',
  );
}
